- type: startingGear
  id: SpecialOfficerGear
  equipment:
    jumpsuit: ClothingUniformJumpskirtSpecialOfficer
    neck: ClothingNeckCloakSpecialOfficer
    back: ClothingBackpackCallERTLeaderFilled
    mask: ClothingMaskGasSwat
    shoes: ClothingShoesBootsJackSpecialOfficer
    head: ClothingHeadHatSpecialOfficer
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    id: DeadSquadPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltHolsterSpecialOfficer

- type: entity ## Спавнер
  noSpawn: false
  parent: MobHuman
  id: SpecialOfficerPreset
  name: Special Officer
  suffix: ДСО
  components:
    - type: RandomMetadata
      nameSegments:
      - SpecialOfficerName
      - names_last
    - type: Loadout
      prototypes: [ SpecialOfficerGear ]
    - type: RandomHumanoidAppearance
      randomizeName: false
    - type: AutoImplant
      implants:
      - MindShieldImplant

- type: dataset ## Датасет, чтобы ОСО начинался с офицер
  id: SpecialOfficerName
  values:
  - Офицер
